# Generated by Django 4.2.27 on 2026-01-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyboard",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
